version: '3'
services:
  redis:
    image: 'redis'
  api:
      build:
        dockerfile: Dockerfile.dev
        context: ./powerapi
      volumes:
        - ./powerapi:/app
      ports:
        - '8000:8000'
